---

# with proxy settings, use_proxy: true
- name: Install Docker engine
  hosts: "all"
  become: yes
  roles:
    - { role: dbs_docker, tags: ["awsclient"], when: use_proxy, environment: [http_proxy: "{{ proxy }}", https_proxy: "{{ proxy }}"] }
    - { role: dbs_docker, tags: ["awsclient"], when: not use_proxy }

