---
- hosts: all
  become: yes
  serial: 1

  vars:
  - os_distribution: Ubuntu
  - os_version: 14.04

  tasks:
    - name: update apt cache
      apt: update_cache=yes

  roles:
    - common
    - docker


