---

# play 1
- name: Installing and configuring Docker 
  hosts: all
  become: yes
  serial: 1

  vars: 
  - os_distribution: Ubuntu
  - os_version: 14.04

  roles:
    - { role: dbs_docker, tags: ["docker"] }

# play 2
- name: Setting up Rancher server
  hosts: "rancher_server"
  become: yes
  roles:
    - { role: dbs_rancher_server, tags: ["rancher_server"] }

# play 3
- name: Register Rancher Hosts
  hosts: "rancher_node"
  become: yes
  serial: 1
  roles:
    - { role: dbs_rancher_agent, tags: ["rancher_agent"] }


