# - src: https://github.com/dhessenm/dbs_proxyconf
#   name: dbs_proxyconf
#   version: master

# - src: https://github.com/dhessenm/dbs_common
#   name: dbs_common
#   version: master

- src: https://github.com/dhessenm/dbs_docker
  name: dbs_docker
  version: master

- src: https://github.com/dhessenm/dbs_rancher_server
  name: dbs_rancher_server
  version: master

- src: https://github.com/dhessenm/dbs_rancher_node
  name: dbs_rancher_node
  version: master

- src: https://github.com/dhessenm/dbs_awsclient
  name: dbs_awsclient
  version: master

